In [1387]:
import numpy as np

In [1388]:
import pandas as pd

In [1389]:
dataset = pd.read_csv("train House).csv")
sale_price = dataset['SalePrice']
dataset = dataset.drop(columns = ["SalePrice"])
dataset = dataset.drop(columns = ["Id"])

In [1390]:
columns_with_missing_data = dataset.columns[dataset.isnull().any()].tolist()
print(columns_with_missing_data) 

['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature']


In [1391]:
numcols = dataset.select_dtypes(include = ["int64" , "float64"]).columns
print(numcols)  

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold'],
      dtype='object')


In [1392]:
missing_numerical_columns = dataset[numcols].isnull().sum()
missing_numerical_columns = missing_numerical_columns[missing_numerical_columns > 0].index.tolist()
print(missing_numerical_columns) 

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']


In [1393]:
missing_numerical_columns = dataset[numcols].isnull().sum()
missing_numerical_columns = missing_numerical_columns[missing_numerical_columns > 0]
print(missing_numerical_columns)  

LotFrontage    259
MasVnrArea       8
GarageYrBlt     81
dtype: int64


In [1394]:
from sklearn.impute import SimpleImputer
Numimputer = SimpleImputer(strategy='mean') 
dataset[numcols] = Numimputer.fit_transform(dataset[numcols])

In [1395]:
catcols = dataset.select_dtypes(include=['object']).columns
print(catcols)

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')


In [1396]:
missing_categorical_values = dataset[catcols].isnull().sum()
missing_categorical_columns = missing_categorical_values[missing_categorical_values > 0]
print(missing_categorical_columns)

Alley           1369
MasVnrType       872
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64


In [1397]:
dataset = dataset.drop(columns = ["Alley" , "MasVnrType" , "FireplaceQu" , "PoolQC" , "Fence" , "MiscFeature"])

In [1398]:
dataset.info

<bound method DataFrame.info of       MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0           60.0       RL         65.0   8450.0   Pave      Reg         Lvl   
1           20.0       RL         80.0   9600.0   Pave      Reg         Lvl   
2           60.0       RL         68.0  11250.0   Pave      IR1         Lvl   
3           70.0       RL         60.0   9550.0   Pave      IR1         Lvl   
4           60.0       RL         84.0  14260.0   Pave      IR1         Lvl   
...          ...      ...          ...      ...    ...      ...         ...   
1455        60.0       RL         62.0   7917.0   Pave      Reg         Lvl   
1456        20.0       RL         85.0  13175.0   Pave      Reg         Lvl   
1457        70.0       RL         66.0   9042.0   Pave      Reg         Lvl   
1458        20.0       RL         68.0   9717.0   Pave      Reg         Lvl   
1459        20.0       RL         75.0   9937.0   Pave      Reg         Lvl   

     Utilities LotC

In [1399]:
catcols = dataset.select_dtypes(include=['object']).columns

In [1400]:
missing_categorical_values = dataset[catcols].isnull().sum()

missing_categorical_columns = missing_categorical_values[missing_categorical_values > 0]
print(missing_categorical_columns) 

BsmtQual        37
BsmtCond        37
BsmtExposure    38
BsmtFinType1    37
BsmtFinType2    38
Electrical       1
GarageType      81
GarageFinish    81
GarageQual      81
GarageCond      81
dtype: int64


In [1401]:
from sklearn.impute import SimpleImputer
Cimputer = SimpleImputer(strategy='most_frequent') 

In [1402]:
dataset[catcols]  = Cimputer.fit_transform(dataset[catcols]) 

In [1403]:
colstring = ['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional',
       'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive',
       'SaleType', 'SaleCondition']

In [1404]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
colT = ColumnTransformer(
    transformers=[("encoder", OneHotEncoder(sparse_output=False, handle_unknown='ignore'), colstring)], 
    remainder="passthrough"
) 

In [1405]:
df_encoded = colT.fit_transform(dataset) 
print(df_encoded)

[[0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 2.000e+00 2.008e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 5.000e+00 2.007e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 9.000e+00 2.008e+03]
 ...
 [0.000e+00 0.000e+00 0.000e+00 ... 2.500e+03 5.000e+00 2.010e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 4.000e+00 2.010e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 6.000e+00 2.008e+03]]


In [1406]:
print(type(df_encoded)) 

<class 'numpy.ndarray'>


In [1407]:
ohe_feature_names = colT.named_transformers_['encoder'].get_feature_names_out(colstring) 
feature_names = list(ohe_feature_names) + [col for col in dataset.columns if col not in colstring]
df_encoded = pd.DataFrame(df_encoded, columns=feature_names)  

In [1408]:
dataset = df_encoded

In [1409]:
X = dataset

In [1410]:
print(X)

      MSZoning_C (all)  MSZoning_FV  MSZoning_RH  MSZoning_RL  MSZoning_RM  \
0                  0.0          0.0          0.0          1.0          0.0   
1                  0.0          0.0          0.0          1.0          0.0   
2                  0.0          0.0          0.0          1.0          0.0   
3                  0.0          0.0          0.0          1.0          0.0   
4                  0.0          0.0          0.0          1.0          0.0   
...                ...          ...          ...          ...          ...   
1455               0.0          0.0          0.0          1.0          0.0   
1456               0.0          0.0          0.0          1.0          0.0   
1457               0.0          0.0          0.0          1.0          0.0   
1458               0.0          0.0          0.0          1.0          0.0   
1459               0.0          0.0          0.0          1.0          0.0   

      Street_Grvl  Street_Pave  LotShape_IR1  LotShape_IR2  Lot

In [1411]:
y = sale_price


In [1412]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()

X_ss = pd.DataFrame(standard_scaler.fit_transform(X), columns=X.columns)

In [1413]:
from sklearn.ensemble import RandomForestRegressor 
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0) 
regressor.fit(X_ss, y)

RandomForestRegressor(random_state=0)

In [1414]:
dataframe = pd.read_csv("test.csv") 
id = dataframe["Id"]
Xtest = dataframe.iloc[:,1:] 

In [1415]:
numcols = Xtest.select_dtypes(include = ["int64" , "float64"]).columns

In [1416]:
Xtest[numcols] = Numimputer.transform(Xtest[numcols]) 

In [1417]:
Xtest = Xtest.drop(columns = ["Alley" , "MasVnrType" , "FireplaceQu" , "PoolQC" , "Fence" , "MiscFeature"])

In [1418]:
catcols = Xtest.select_dtypes(include=['object']).columns

In [1419]:
Xtest[catcols]  = Cimputer.transform(Xtest[catcols]) 

In [1420]:
df_encoded = colT.transform(Xtest)

In [1421]:
ohe_feature_names = colT.named_transformers_['encoder'].get_feature_names_out(colstring) 
feature_names = list(ohe_feature_names) + [col for col in Xtest.columns if col not in colstring]
df_encoded = pd.DataFrame(df_encoded, columns=feature_names)  

In [1422]:
Xtest = df_encoded 

In [1423]:
X_ss = pd.DataFrame(standard_scaler.transform(Xtest), columns=X.columns) 

In [1424]:
y_pred = regressor.predict(X_ss)

In [1425]:
print(y_pred)

[127864.5  155169.9  177370.44 ... 148498.21 113486.5  223649.4 ]


In [1426]:
print(id)

0       1461
1       1462
2       1463
3       1464
4       1465
        ... 
1454    2915
1455    2916
1456    2917
1457    2918
1458    2919
Name: Id, Length: 1459, dtype: int64


In [1427]:
print(type(id))

<class 'pandas.core.series.Series'>


In [1428]:
idn = id.values

In [1429]:
print(idn)

[1461 1462 1463 ... 2917 2918 2919]


In [1430]:
import numpy as np
import pandas as pd

# Replace these with your actual NumPy arrays
ids = idn  # e.g., np.array([1461, 1462, 1463, 1464, 1465, 2919])  # e.g., np.array([127864.5, 155169.9, 177370.44, 148498.21, 113486.5, 223649.4])

# Create a DataFrame from the NumPy arrays
output = pd.DataFrame({
    'Id': ids,
    'SalePrice': y_pred
})

# Save the DataFrame to a CSV file
output_file_path = 'predictions.csv'
output.to_csv(output_file_path, index=False)

# Confirm file creation
print(f"File saved as: {output_file_path}")


File saved as: predictions.csv
